name: main
on: push
jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.20.6"

      - name: running
        run: deno run --allow-net --allow-env app.ts
        env:
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
